import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-gray-800 py-4">
          <div className="container mx-auto flex items-center justify-between">
            <a className="text-white text-2xl" href="/">
              Ecommerce
            </a>
            <div className="text-white text-2xl">
              <a className="mr-4" href="/products">
                Products
              </a>
              <a className="mr-4" href="/pricing">
                Pricing
              </a>
              <a className="mr-4" href="/pippo">
                Pippo
              </a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}